image: python:2-alpine

before_script:
  - pip install -r requirements-dev.txt

stages:
  - local_test
  - deploy
  - contract_test

unit_test:
  stage: local_test
  script:
    - python -m unittest discover --start-directory test/unit

integration_test:
  stage: local_test
  services:
    - dwmkerr/dynamodb:latest
  variables:
    DYNAMODB_HOST: dwmkerr-dynamodb
  before_script:
    - pip install -r requirements-dev.txt
    - python test/local/table.py create
    - python test/local/table.py populate
  script:
    - python -m unittest discover --start-directory test/integration

deploy:
  stage: deploy
  image: node:alpine
  before_script:
    - npm install -g serverless
  script:
    - serverless deploy
    - echo "export SERVICE_ENDPOINT=$(serverless info --verbose | grep ServiceEndpoint | cut -d" " -f2)" >> variables
  artifacts:
    paths:
      - variables
    expire_in: 1 hour
  only:
    - master

contract_test:
  stage: contract_test
  script:
    - source variables
    - python -m unittest discover --start-directory test/contract
  only:
    - master
