image: python:2-alpine

before_script:
  - pip install -r requirements-dev.txt

stages:
  - local_test
  - deploy
  - contract_test

unit_test:
  stage: local_test
  script:
    - python -m unittest discover --start-directory test/unit

integration_test:
  stage: local_test
  script:
    - python -m unittest discover --start-directory test/integration

deploy:
  stage: deploy
  image: node:alpine
  before_script:
    - npm install -g serverless
  script:
    - serverless deploy

contract_test:
  stage: contract_test
  script:
    - python -m unittest discover --start-directory test/contract
