service: xref-service-${opt:type, self:custom.defaultType}
custom:
  defaultType: generic
  defaultStage: dev
  profiles:
    dev: default
    test: ecommtest
provider:
  name: aws
  runtime: python2.7
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}
  region: eu-west-1
  timeout: 30
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}-${opt:type, self:custom.defaultType}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}*

package:
 exclude:
   - env/**
   - test/**

functions:
  get_ids:
    handler: handler.get_ids
    events:
      - http:
          path: ${self:service}/{system1}/{system1_id}
          method: get
  new_global_id:
    handler: handler.new_global_id
    events:
      - http:
          path: ${self:service}/global/
          method: post
  link_system_ids:
    handler: handler.link_system_ids
    events:
      - http:
          path: ${self:service}/{system1}/{system1_id}/{system2}/{system2_id}
          method: put
  delete_id:
    handler: handler.delete_id
    events:
      - http:
          path: ${self:service}/{system1}/{system1_id}
          method: delete

resources:
  Resources:
    XrefServiceDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: global
            AttributeType: S
          -
            AttributeName: m3
            AttributeType: S
          -
            AttributeName: tp
            AttributeType: S
        KeySchema:
          -
            AttributeName: global
            KeyType: HASH
        GlobalSecondaryIndexes:
        - IndexName: m3_system
          KeySchema:
          - AttributeName: m3
            KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: tp_system
          KeySchema:
          - AttributeName: tp
            KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
